name: pyor
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - sympy
  - pillow
  - ipykernel
  - ipywidgets
  - ipympl
  - jupyterlab
  - joblib
  - pip
  - pip:
      - diffrax
      - equinox
      - numba
      - tqdm
      - pyyaml
